### ISSUE TITLE
Sequel support

### ISSUE THREAD

**Issue by gencer** [dejan/rails_panel#126] opened 2017-05-29 13:58 UTC
Is it possible to get some profiling for Sequel? I see that if we run DB queries, RailsPanel shows how much time spent in ActiveRecord field but does not show any query in ActiveRecord tab as expected.

**Comment by modosc** [comment] 2017-05-29 18:29
are you using [sequel-rails](https://github.com/TalentBox/sequel-rails)

**Comment by gencer** [comment] 2017-05-29 18:51
@modosc, yes.

**Comment by modosc** [comment] 2017-05-30 00:47
pretty sure the issue is that `sequel-rails` emits a `sql.sequel` event:

https://github.com/TalentBox/sequel-rails/blob/d4babb6b0ff2e52bc26cb5f48288d560c2233469/lib/sequel_rails/railtie.rb#L25

but `rails_panel` is only subscribing to `sql.active_record:

https://github.com/dejan/rails_panel/blob/442e3d29c710aa532d0ba17972f6076d6d0094f6/meta_request/lib/meta_request/app_notifications.rb#L40

just duplicating that section with `sql.sequel` would probably resolve this issue - i'm not sure it's the right solution though, i'm unclear on how common a situation is it to replace `activerecord` with `sequel`.

**Comment by gencer** [comment] 2017-05-30 07:10
I was trying what you point here, seems we have to at least check somehow before emit?

Duplicating that block with `sql.sequel` gave:
`SystemStackError: stack level too deep (Sequel::DatabaseConnectionError)`

**Comment by gencer** [comment] 2017-05-30 07:35
@modosc, regarding to my previous reply, I simply tried to check whatever connection is OK by using `Sequel::Model.db.test_connection` but this time I start to get Sequel's threading sync error.

Somehow, either we try to get log before connection OR there is one more step for sequel emit which is beyond my knowledge here.

**Comment by modosc** [comment] 2017-05-30 15:33
if you setup a test repo for this i'll take a look.

**Comment by gencer** [comment] 2017-05-30 16:35
@modosc, sure! Here we go: https://github.com/gencer/SequelRailsPanelTest

I tested, RailsPanel successfully capture the data behind request. You should see `{"id":1,"some_column":"SequelRails"}` as output in browser when hit to `'/'`. But without Sequel of course.

**Comment by gencer** [comment] 2017-06-03 08:29
@modosc, just a curiosity, did you have any improvements on this or did you have managed to work on sample?

**Comment by modosc** [comment] 2018-04-06 17:04
I merged in the sequel support changes a while back and I just release meta_request 0.6.0. it seems to work with your test branch when I updated it (at least -not seeing the crash). Can you verify?

**Comment by gencer** [comment] 2018-04-06 17:09
@modosc I was using that branch since it exists and I did not see any single issue until now. Only change would be is to change `ActiveRecord` tab name to `SQL`. This will be a better naming strategy. (Probably on chrome ext. side...)

**In short**, yes I verify that change and works as expected.

Thank you for your time and effort!

**Closed** 2018-04-06 17:31 UTC

**Comment by modosc** [comment] 2018-04-06 17:50
Ok closing this for now then .
